STAGE_INPUT_PATTERNS: dict[str, tuple[str, ...]] = {
    "research": (),
    "write": ("research_report.md",),
    "humanize": ("scripts/script.yaml",),
    "source_media": ("source_media",),
    "footage_edit": ("footage_timeline.yaml", "source_media"),
    "pre_production": ("scripts/script.yaml", "director_notes.md"),
    "design": ("scripts/script.yaml", "pipeline/{name}/pre_production.yaml"),
    "screenplay_structure": ("scripts/script.yaml", "design_report.yaml"),
    "director_contract": (
        "design_report.yaml",
        "pipeline/{name}/screenplay_structure.yaml",
        "pipeline/{name}/pre_production.yaml",
    ),
    "reference_plate": (
        "pipeline/{name}/director_contract.yaml",
        "pipeline/{name}/pre_production.yaml",
    ),
    "generate_images": (
        "image_prompts.yaml",
        "image_map.yaml",
        "design_report.yaml",
        "assets/references",
    ),
    "storyboard_sheet": (
        "pipeline/{name}/reference_plates.yaml",
        "design_report.yaml",
        "assets/images",
    ),
    "animatic": (
        "pipeline/{name}/reference_plates.yaml",
        "assets/images",
        "assets/storyboard",
    ),
    "production_readiness": (
        "scripts/script.yaml",
        "pipeline/{name}/director_contract.yaml",
        "pipeline/{name}/reference_plates.yaml",
        "pipeline/{name}/storyboard_sheet.yaml",
        "pipeline/{name}/animatic.yaml",
    ),
    "generate_video": (
        "design_report.yaml",
        "pipeline/{name}/director_contract.yaml",
        "pipeline/{name}/reference_plates.yaml",
        "pipeline/{name}/production_readiness.yaml",
        "pipeline/{name}/video_regen_queue.yaml",
        "assets/images",
    ),
    "take_select": (
        "assets/videos",
        "pipeline/{name}/director_contract.yaml",
        "pipeline/{name}/video_gen_state.json",
    ),
    "generate_tts": ("scripts/script.yaml",),
    "film_timeline": (
        "scripts/script.yaml",
        "design_report.yaml",
        "image_map.yaml",
        "assets/images",
        "assets/videos",
        "assets/tts",
        "footage_timeline.yaml",
        "pipeline/{name}/take_selection.yaml",
    ),
    "remotion_preview": ("film_timeline.yaml",),
    "film_assemble": ("film_timeline.yaml", "pipeline/{name}/remotion_preview.yaml"),
    "generate_music": ("scripts/script.yaml", "pipeline/{name}/timing.json"),
    "remix_audio": ("assets/tts", "assets/music", "pipeline/{name}/timing.json"),
    "kenburns": (
        "assets/images",
        "image_map.yaml",
        "pipeline/{name}/timing.json",
    ),
    "concat": ("pipeline/{name}/video_segments",),
    "audio": ("pipeline/{name}/film_assembled.mp4", "pipeline/{name}/mixed_audio.mp3"),
    "subtitles": ("output/{name}-clean.mp4", "pipeline/{name}/timing.json"),
    "qa": ("output/{name}-sub.mp4", "film_timeline.yaml"),
    "continuity_bible": (
        "pipeline/{name}/screenplay_structure.yaml",
        "film_timeline.yaml",
        "pipeline/{name}/director_contract.yaml",
    ),
    "editing_review": ("pipeline/{name}/render_report.yaml", "film_timeline.yaml"),
    "director_review": ("pipeline/{name}/render_report.yaml", "film_timeline.yaml"),
    "rework_plan": (
        "pipeline/{name}/director_review.yaml",
        "pipeline/{name}/editing_review.yaml",
        "pipeline/{name}/continuity_bible.yaml",
    ),
    "creative_review": (
        "scripts/script.yaml",
        "film_timeline.yaml",
        "pipeline/{name}/editing_review.yaml",
        "pipeline/{name}/continuity_bible.yaml",
    ),
    "visual_semantic_qa": (
        "film_timeline.yaml",
        "pipeline/{name}/director_contract.yaml",
        "pipeline/{name}/render_report.yaml",
    ),
    "film_supervisor": (
        "pipeline/{name}/rework_plan.yaml",
        "pipeline/{name}/creative_review.yaml",
        "pipeline/{name}/visual_semantic_report.yaml",
        "pipeline/{name}/render_report.yaml",
    ),
    "assistant_handoff": (
        "pipeline/{name}/film_supervisor.yaml",
        "pipeline/{name}/production_readiness.yaml",
        "pipeline/{name}/render_report.yaml",
    ),
    "rework_execute": ("pipeline/{name}/rework_plan.yaml",),
}


STAGE_OUTPUT_PATTERNS: dict[str, tuple[str, ...]] = {
    "research": ("research_report.md",),
    "write": ("scripts/script.yaml", "scripts/script_raw.yaml"),
    "humanize": ("scripts/script.yaml",),
    "source_media": ("asset_manifest.yaml", "footage_timeline.yaml"),
    "footage_edit": ("pipeline/{name}/footage_roughcut.mp4",),
    "pre_production": ("pipeline/{name}/pre_production.yaml",),
    "design": ("image_prompts.yaml", "image_map.yaml", "design_report.yaml"),
    "screenplay_structure": ("pipeline/{name}/screenplay_structure.yaml",),
    "director_contract": ("pipeline/{name}/director_contract.yaml",),
    "reference_plate": ("pipeline/{name}/reference_plates.yaml",),
    "generate_images": ("pipeline/{name}/image_gen_state.json", "assets/images"),
    "storyboard_sheet": ("pipeline/{name}/storyboard_sheet.yaml",),
    "animatic": ("pipeline/{name}/animatic.yaml", "pipeline/{name}/animatic.mp4"),
    "production_readiness": ("pipeline/{name}/production_readiness.yaml",),
    "generate_video": ("pipeline/{name}/video_gen_state.json", "assets/videos"),
    "take_select": ("pipeline/{name}/take_selection.yaml",),
    "generate_tts": ("pipeline/{name}/timing.json", "pipeline/{name}/tts_state.json"),
    "film_timeline": ("film_timeline.yaml",),
    "remotion_preview": ("pipeline/{name}/remotion_preview.yaml",),
    "film_assemble": ("pipeline/{name}/film_assembled.mp4",),
    "generate_music": ("pipeline/{name}/bgm_state.json",),
    "remix_audio": ("pipeline/{name}/mixed_audio.mp3",),
    "kenburns": ("pipeline/{name}/video_segments",),
    "concat": ("pipeline/{name}/final_nosub.mp4",),
    "audio": ("output/{name}-clean.mp4",),
    "subtitles": ("output/{name}-sub.mp4",),
    "qa": ("pipeline/{name}/render_report.yaml",),
    "continuity_bible": ("pipeline/{name}/continuity_bible.yaml",),
    "editing_review": ("pipeline/{name}/editing_review.yaml",),
    "director_review": ("pipeline/{name}/director_review.yaml",),
    "rework_plan": ("pipeline/{name}/rework_plan.yaml",),
    "creative_review": ("pipeline/{name}/creative_review.yaml",),
    "visual_semantic_qa": ("pipeline/{name}/visual_semantic_report.yaml",),
    "film_supervisor": ("pipeline/{name}/film_supervisor.yaml",),
    "assistant_handoff": (
        "pipeline/{name}/assistant_handoff.yaml",
        "pipeline/{name}/assistant_handoff.md",
    ),
    "rework_execute": ("pipeline/{name}/rework_execution.yaml",),
}


def stage_input_patterns(stage_name: str) -> tuple[str, ...]:
    return STAGE_INPUT_PATTERNS.get(stage_name, ())


def stage_output_patterns(stage_name: str) -> tuple[str, ...]:
    return STAGE_OUTPUT_PATTERNS.get(stage_name, ())
