from __future__ import annotations

from pathlib import Path

import yaml

from narrascape.agent.models import ShotDesign
from narrascape.cache import BuildCache
from narrascape.config import (
    ImageConfig,
    ImageProvider,
    LLMConfig,
    NarrascapeConfig,
    PipelineConfig,
    ProjectConfig,
    ShotType,
    load_script,
)
from narrascape.pipeline import Pipeline
from narrascape.stages.base import StageContext, StageResult
from narrascape.stages.design import DesignStage
from narrascape.stages.pre_production import PreProductionStage


def _write_script(project_dir: Path) -> None:
    (project_dir / "scripts").mkdir(parents=True, exist_ok=True)
    (project_dir / "scripts" / "script.yaml").write_text(
        yaml.safe_dump(
            {
                "segments": [
                    {
                        "id": 1,
                        "text": "A student stands in a cramped room under sickly window light.",
                    }
                ]
            },
            sort_keys=False,
        ),
        encoding="utf-8",
    )


def _config(
    project_dir: Path,
    *,
    strict_director: bool = False,
    llm_mode: str = "none",
) -> NarrascapeConfig:
    _write_script(project_dir)
    return NarrascapeConfig(
        project=ProjectConfig(
            name="strict-director-real-stage",
            title="Strict Director Real Stage",
            script_file="scripts/script.yaml",
        ),
        pipeline=PipelineConfig(strict_director=strict_director),
        llm=LLMConfig(mode=llm_mode),
        images=ImageConfig(provider=ImageProvider.LOCAL),
        project_dir=project_dir,
    )


def _context(config: NarrascapeConfig) -> StageContext:
    return StageContext(
        config=config,
        script=load_script(config.script_path),
        cache=BuildCache(config.pipeline_dir / ".cache"),
    )


class FailingLLM:
    def run_template_validated(self, *args, **kwargs):
        raise RuntimeError("LLM unavailable")

    def complete(self, *args, **kwargs):
        raise RuntimeError("LLM unavailable")


def test_pre_production_report_marks_not_configured_without_llm(tmp_path):
    config = _config(tmp_path / "project")

    result = PreProductionStage(llm_client=None).run(_context(config))

    assert result.success is True
    report = yaml.safe_load(
        (config.pipeline_dir / "pre_production.yaml").read_text(encoding="utf-8")
    )
    assert report["director_process"]["llm_status"] == "not_configured"


def test_pre_production_report_marks_fallback_after_llm_error(tmp_path):
    config = _config(tmp_path / "project", llm_mode="ai_assistant")

    result = PreProductionStage(llm_client=FailingLLM()).run(_context(config))

    assert result.success is True
    report = yaml.safe_load(
        (config.pipeline_dir / "pre_production.yaml").read_text(encoding="utf-8")
    )
    assert report["director_process"]["llm_status"] == "fallback_after_error"
    assert report["director_process"]["errors"]


def test_design_report_marks_not_configured_without_llm(tmp_path):
    config = _config(tmp_path / "project")
    PreProductionStage(llm_client=None).run(_context(config))

    result = DesignStage(llm_client=None).run(_context(config))

    assert result.success is True
    report = yaml.safe_load((config.pipeline_dir / "design_report.yaml").read_text("utf-8"))
    assert report["director_process"]["llm_status"] == "not_configured"


def test_design_report_marks_fallback_when_script_analysis_falls_back(tmp_path, monkeypatch):
    class FakePromptDirector:
        def __init__(self, llm_client):
            self.llm_client = llm_client

        def design_sequence(self, segments, analysis_list, config, storyboard=None):
            return [
                ShotDesign(
                    segment_id=segments[0].id,
                    shot_type=ShotType.MEDIUM,
                    image_prompt="A cinematic image generated by the prompt director.",
                    reasoning="Prompt director still succeeded after analysis fallback.",
                )
            ]

        def get_consistency_anchor(self):
            return {}

    config = _config(tmp_path / "project", llm_mode="ai_assistant")
    PreProductionStage(llm_client=None).run(_context(config))
    monkeypatch.setattr("narrascape.stages.design.PromptDirector", FakePromptDirector)

    result = DesignStage(llm_client=FailingLLM()).run(_context(config))

    assert result.success is True
    report = yaml.safe_load((config.pipeline_dir / "design_report.yaml").read_text("utf-8"))
    assert report["director_process"]["llm_status"] == "fallback_after_error"
    assert report["director_process"]["steps"]["script_analysis"]["llm_status"] == (
        "fallback_after_error"
    )


def test_strict_director_mode_rejects_real_pre_production_fallback(tmp_path, monkeypatch):
    class LaterStage:
        name = "design"
        depends_on = ["pre_production"]

        def can_run(self, context):
            return True, ""

        def run(self, context):
            raise AssertionError("strict director failure should stop design")

    config = _config(
        tmp_path / "project",
        strict_director=True,
        llm_mode="ai_assistant",
    )
    monkeypatch.setattr(
        "narrascape.pipeline.STAGE_MAP",
        {
            "pre_production": PreProductionStage,
            "design": LaterStage,
        },
    )

    results = Pipeline(config, auto_approve=True, llm_client=FailingLLM()).run(stages=["design"])

    assert results["pre_production"].success is False
    assert "fallback_after_error" in results["pre_production"].message
    assert "design" not in results


def test_strict_director_mode_rejects_real_design_not_configured(tmp_path, monkeypatch):
    class PreProductionPassthrough:
        name = "pre_production"
        depends_on = []

        def can_run(self, context):
            return True, ""

        def run(self, context):
            output = context.config.pipeline_dir / "pre_production.yaml"
            output.parent.mkdir(parents=True, exist_ok=True)
            output.write_text(
                yaml.safe_dump(
                    {
                        "director_process": {
                            "mode": "llm_visual_pre_production",
                            "llm_status": "used",
                        },
                        "characters": [],
                        "environments": [],
                        "storyboard": {"frames": [], "total_frames": 0},
                    },
                    sort_keys=False,
                ),
                encoding="utf-8",
            )
            return StageResult("pre_production", True, outputs=[output])

    config = _config(tmp_path / "project", strict_director=True)
    monkeypatch.setattr(
        "narrascape.pipeline.STAGE_MAP",
        {
            "pre_production": PreProductionPassthrough,
            "design": DesignStage,
        },
    )

    results = Pipeline(config, auto_approve=True, llm_client=None).run(stages=["design"])

    assert results["pre_production"].success is True
    assert results["design"].success is False
    assert "not_configured" in results["design"].message


def test_strict_director_mode_rejects_cached_director_artifact(tmp_path, monkeypatch):
    class CachedDirectorContract:
        name = "director_contract"
        depends_on = []
        outputs = ["pipeline/{name}/director_contract.yaml"]

        def can_run(self, context):
            return True, ""

        def run(self, context):
            raise AssertionError("cached director artifact should be checked before skip")

    config = _config(
        tmp_path / "project",
        strict_director=True,
        llm_mode="ai_assistant",
    )
    pipeline = Pipeline(config, auto_approve=True, llm_client=object())
    artifact = config.pipeline_dir / "director_contract.yaml"
    artifact.parent.mkdir(parents=True, exist_ok=True)
    artifact.write_text(
        yaml.safe_dump(
            {
                "schema_version": "director_contract.v1",
                "compile_process": {
                    "mode": "deterministic_prompt_compiler",
                    "llm_status": "not_configured",
                },
                "shots": [],
            },
            sort_keys=False,
        ),
        encoding="utf-8",
    )
    pipeline.state.set_stage_status("director_contract", "completed")
    pipeline.state.set_stage_outputs("director_contract", [str(artifact)])
    pipeline.approval.approve("director_contract", reviewer="test")
    monkeypatch.setattr(
        "narrascape.pipeline.STAGE_MAP",
        {"director_contract": CachedDirectorContract},
    )

    results = pipeline.run(stages=["director_contract"])

    assert results["director_contract"].success is False
    assert "not_configured" in results["director_contract"].message
